### ISSUE TITLE
DB Designer don't save custom generated tables

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#10]
Hi !

I did a N-N relation in the DB designer, then changed the name of the generated table.
When I save it, no changes are made to the DB. When I go back to defaults, it works fine.
And when I change it again with new properties, changes are made in the DB.
The problem is when you design a new relation and rename it _before_ saving it.

**Comment by parsimony** [comment]
Ok, thanks for your feedback.
This issue is now resolved :)

**Comment by mtancoigne** [comment]
Great :+1:
