### ISSUE TITLE
"Successfull Installation" - NOT

### ISSUE THREAD

**Issue by Cinux90** [parsimony/parsimony#100]
I wont to try parsimony. The Demo at the website wont work. "Wrong Username or Password". Whatever. So i want to run it in a vm.
All was good. I was showed "Congratulations, Parsimony is now ready" but when i klick on the link "Let´s Go" i get an 404 Error. I dont know why. The URL was localhost/parsimony/connect/

Only the site localhost/parsimony/ work. but not realy good. Behind every link its also an 404 Error. Its looks like the setup was failed. But i dont know why?

Can somebody help?

**Comment by parsimony** [comment]
Hi 
Thank you for your feedback!
The demo is updated and works. Hope you have fun with it.

Concerning the 404 error, it's a configuration issue. Can you give me more informations about your web hosting?

**Comment by parsimony** [comment]
Perhaps super easy no "/" after connect. Try it!

**Comment by Cinux90** [comment]
Thx for your awnser.

The "/" at the end of the URL was a issue by writing this post. Sorry. So without the "/" i get also the 404 Error.

The configuration of my Webhost is easy. I use a fresh Debian 7.5 and installed all necessary components with apt-get.

"apt-get install php5 apache2 php5-mysql php5-curl mysql-server"

After that i dont change a configuration of the webhost, becuase the setup von parsimony say all its ok for the install. Must i configure something more?

**Comment by parsimony** [comment]
Are your "index.php" and ".htaccess" files in the project's root folder ?

**Comment by Cinux90** [comment]
Yes, there are.

Thats the complet folder:

-rw-r--r--  1 www-data www-data   399 Jul 22 07:34 .gitignore
-rw-r--r--  1 www-data www-data   215 Jul 22 07:34 .htaccess
-rw-r--r--  1 www-data www-data  1133 Jul 22 07:35 index.php
-rw-r--r--  1 www-data www-data 51092 Jul 22 07:35 installNewLife.php
drwx------ 13 www-data www-data  4096 Jul 21 13:22 lib
-rw-r--r--  1 www-data www-data 10029 Jul 22 07:34 LICENSE.txt
drwx------  5 www-data www-data  4096 Jul 21 13:22 modules
drwxr-xr-x  3 www-data www-data  4096 Jul 21 13:23 profiles
-rw-r--r--  1 www-data www-data  2071 Jul 22 07:34 README.md
drwx------  3 www-data www-data  4096 Jul 21 13:22 var

i can open http://localhost/parsimony-master/index.php and get an webpage without any styles. 
![website](https://cloud.githubusercontent.com/assets/3616240/3655438/af69be8a-1179-11e4-8b26-a6823812067f.jpg)

**Comment by parsimony** [comment]
I have a few questions & purposes.

The code in index.php is interpreted. So this may be a problem with file path.
- Is the mode mod_rewrite enabled? 
- Is the user_dir enabled?
- What is your BASE_PATH in config.php?

Can you add the following code in the config.php ?
$config['DOCUMENT_ROOT'] = **DIR**;

Thanks for your reply

**Comment by parsimony** [comment]
Can you also read the following issue https://github.com/parsimony/parsimony/issues/47 and try particularly the point about .htaccess?

Thank you for your contribution

**Comment by Cinux90** [comment]
mod_rewrite was enabled.

What did you mean with "user_dir" ?

The  "BASE_PATH" from /var/www/parsimony-master/profiles/www/config.php is $config['BASE_PATH'] = '/parsimony-master/';
and so the right path.

OK with your last link i think now its solve.

The solution is discripte here -> https://github.com/parsimony/parsimony/issues/12#issuecomment-10439503

Thank you :)
