### ISSUE TITLE
DBmanager : delete a table

### ISSUE THREAD

**Issue by chessman2212** [parsimony/parsimony#11]
Hello,

seems to work like a charm unless you create too much tables like I did several times :)

How to delete a table in a specific module ?

**Comment by mtancoigne** [comment]
Hi !

The easy way is to click on the upper right corner of one of your tables in  the DB designer, I guess the "X" icon is missing, but the link exists. Then, a little javascript alert pops up, you say yes, and the table is gone. Don't forget to save your changes :)

Hope it helped.

**Comment by parsimony** [comment]
The delete button is back in nightly :)

Thanks for feedback !
