### ISSUE TITLE
"/blabla/connect" Not Found after install

### ISSUE THREAD

**Issue by guiguid** [parsimony/parsimony#12]
Branch Master lastest revision

At the end of install : 

Not Found

The requested URL /web/connect was not found on this server.

parsimony installed on /var/www/parsimony
with Alias : /web /var/www/parsimony

install works fine

but can't reach "connect".

base http://monsupersite/web  show pure html file (with no css img and other)

log are : 
File does not exist: /var/www/parsimony/connect
File does not exist: /var/www/parsimony/core, referer: http://monsupersite/web/

**Comment by mtancoigne** [comment]
Do you have mod_rewrite installed and configured ?

Try with "/blabla/?parsiurl=connect"

If this works, the problem is about mod_rewrite.

**Comment by guiguid** [comment]
"/web/?parsiurl=connect"   only html works ( no img )

but 

everything is in green when doing install.

 a2enmod rewrite
Module rewrite already enabled

phpinfo() 
Loaded Modules : .... mod_rewrite .....

log : 
File does not exist: /var/www/parsimony/admin, referer: http://monsupersite/web/?parsiurl=connect

**Comment by mtancoigne** [comment]
Look at your .htaccess in the /parsimony directory and add this line after `RewriteEngine On` :

`RewriteBase /web`

and try again ;)

**Comment by guiguid** [comment]
already tested

RewriteBase /web/
RewriteBase /web
RewriteBase /
and 
#RewriteBase /web/

File does not exist: /var/www/parsimony/connect

or 
File does not exist: /var/www/parsimony/concat, referer: http://monsupersite/web/

I have also commented the ifmodule part, but no luck

I don't know where to look : 

 cat /etc/apache2/conf.d/parsimony 
Alias /web /var/www/parsimony
<Directory /var/www/parsimony>
        Order allow,deny
        Allow from all
    Options None
  <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresDefault M310
   </IfModule>
</Directory> 

 cat /var/www/parsimony/.htaccess 

<IfModule mod_rewrite.c>
  RewriteEngine on

  #Uncomment following line and modify username if you use UserDir mod
  RewriteBase /web/

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]
</IfModule>

**Comment by mtancoigne** [comment]
have you read this thread : https://github.com/parsimony/parsimony_cms/issues/8 (fr)?

It solved the problem for me (an install ou of /var/www, using user_dir), I think the problem is close to this one, but the changes haven't been commit to sources.

If you need a translation of the solution in english, tell me :)

**Comment by guiguid** [comment]
SOLVED ! 

cat /etc/apache2/conf.d/parsimony 
Alias /web /var/www/parsimony
<Directory /var/www/parsimony>
        Order allow,deny
        Allow from all
#  Options None
        AllowOverride All
    <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresDefault M310
    </IfModule>
</Directory> 

-> disabed Options none
-> be sure to have AllowOverride All

thanks.

**Comment by jojolalpin** [comment]
A newbee comment on installation if it can help
install on ubuntu 12.04, apache 2.2.22, php 5.3.10 (lamp install)
Changing AllowOverride in site conf did not make anything.
To make it work (.htaccess was not interpreted) I just had to add to /etc/apache2/httpd.conf:
&lt;Directory /var/www/parsimony&gt;
    AllowOverride All
&lt;/Directory&gt;

**Comment by parsimony** [comment]
:+1:
