### ISSUE TITLE
No underscores in table names

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#13]
Hello !

When you create a table using the Designer, the table is not created in DB if its name contains underscore (_).

**Comment by parsimony** [comment]
I can't reproduce this behavior, can you give me the name of your table ?

**Comment by mtancoigne** [comment]
yes, it's "champ_type", wich is linked to a "champ" table. I try to set up a contact manager with unlimited fields for each contacts.

**Comment by parsimony** [comment]
II just tested this case in DB designer, and it works, can you tell me all fields of your tables, or send us a screenshot by mail ?

**Comment by mtancoigne** [comment]
In a module named "contacts", I have three tables :
- contact(**id**, nom, est_client, est_fournisseur)
- champ(**id**, nom, valeur, #contact_id, #type_champ_id)
- type_champ(**nom**, description, valid_regexp)

And the last one is not saved in DB...
But if I re-create it with the name "typechamp", it's ok.

**Comment by parsimony** [comment]
I have no problem with this example, could you precise the field types ?

**Comment by mtancoigne** [comment]
Yes, no problem :)
- contact( **id**, nom (string), est_client(state), est_fournisseur(state))
- champ( **id**, nom (string), valeur (string), #contact_id, #type_champ_id)
- type_champ( **nom**, description(string), valid_regexp(string))

And by the way, there is no BOOL field type available (for now...)

I'll try again at home, maybe it's just in a certain case.

**Comment by mtancoigne** [comment]
The problem is always here (I tried to repeat it again, and it's pretty simple :)).

Here is a screenshot of the DBDesigner and a Mysql Workbench view of the DB.
http://hpics.li/c88ee16

The "champ_type" table is not created in DB.

**Comment by parsimony** [comment]
Always no pb for me...

http://hpics.li/cf8a86f

I think it's  a config pb. What's your mySQL version ? and which engine is used to create tables ? (myisam, innodb?)
