### ISSUE TITLE
Wysiwyg

### ISSUE THREAD

**Issue by Anotherdaylight** [parsimony/parsimony#14]
Bonjour, D'abord, je tiens à m'excuser, étant beaucoup plus mail que github, il faut que mon cerveau s'y habitue. Merci

Donc, petites remarques sur le Wysiwyg;
- Lorsque l' on choisi de surligner le texte, il n'y a pas de possibilité de l'enlever. Blanc étant blanc, il manquerait soit l'option carré blanc barré soit "sans" ou "supprimer".
- J'ai remarqué aussi que lorsque j'arrivais sur une balise modifiable wysiwyg la barre d'outils apparaissait (logique jusque là) mais que lorsque que je vais en Création et que je reviens en édition, la barre d'outils n’apparaît plus sauf si j'actualise la page...
- Cela ne se précise peut être pas (tout dépend de l'utilisateur), mais il faut sélectionner le texte avant de modifier le design du texte, ce n'est pas le bloc qui est modifié mais bien le texte sélectionné (oui je sais que certains vont dire "tout le monde le sait..." Détrompez vous...
- De même, toujours pour le lambda, étiqueter les options au survol ne serait pas négligeable (A->A cela vous inspire quoi?)
- Les puces et numérotations??? Toujours pas réussi à comprendre le fonctionnement (Ça fonctionne chez vous?)

Merci... A suivre...

**Comment by parsimony** [comment]
Nous te remercions pour tes remarques. Elles sont notées précieusement.

Nous apporterons ou la communauté apportera des améliorations au Wysiwyg dans les meilleurs délais.

Avec plaisir :)
