### ISSUE TITLE
LeftToolbar / Preview Edit Création

### ISSUE THREAD

**Issue by Anotherdaylight** [parsimony/parsimony#16]
J'en ai déjà parlé en direct mais j'aimerais savoir si d'autres ont ce problème...

La LeftToolbar se trouve chez moi sous le barre preview et donc en mode création l’accès à Blocs n'est pas accessible. Seul solution, agrandir la lefttoolbar vers la gauche, la déplacer puis la réduire... Comme elle revient régulièrement en place, il faut le refaire régulièrement. (par exemple après une mise à jour de la page).
De plus, la barre Preview Edit Création s'affiche sur le haut de l'espace de travail et donc cet endroit devient presque inutilisable...

Je me demande si en la plaçant sur une barre d'outils en bas ne serait pas une idée... (J'y rajouterais un gros boutons sauvegarde ou annulation)...

**Comment by parsimony** [comment]
Ta résolution d'écran doit être inférieure à 1400 ?
Le pb de style est identifié, nous réfléchissons à une solution.

**Comment by Anotherdaylight** [comment]
1280/800 Désolé... Je travail sur une tablette tactile Asus et, justement, avec parsimony, le tactile est très sympa...

**Comment by parsimony** [comment]
It is good news that you work on a tablet with Parsimony.
A specific tablet administration for Parsimony will be realized as soon as possible.
While waiting we enhance tablet compatibility.

**Comment by parsimony** [comment]
En attendant l'admin spécifique pour les tablettes( en cours ), un correctif améliore l'expérience.
