### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by Anotherdaylight** [parsimony/parsimony#17]
Question: Comment enlever un champ dans une table? J'ai bien trouvé ajouter mais pas supprimer...

**Comment by parsimony** [comment]
Je viens de télécharger la dernière version pour faire un test. Il y a bien une croix au survol des champs d'une table. 

Il y a eu une mise à jour du fichier concernant le dbdesigner : parsimony_cms / modules / admin / views / desktop / dbDesigner.php. Tu peux certainement en profiter pour faire une mise à jour globale du projet.

**Comment by Anotherdaylight** [comment]
Tip top, après la mise à jour j'ai bien la croix au survol. Merci.
