### ISSUE TITLE
Default module

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#19]
Hey !!
Is there any option to change the default module ? it's "Parsimony" by default, but what if I want to set a custom one and delete the parsimony module ?

**Comment by parsimony** [comment]
Hey,

Delete core module is impossible because without it Parsimony does'nt work.

Do you want just to rename the module ? If yes it's possible in modules/core/module.php line 33 : `* @title Parsimony`

**Comment by mtancoigne** [comment]
Hum, when I speak of changing the default module, I just want to change the _index_ module, the module by default when you come on the website...

**Comment by parsimony** [comment]
ok, not for now but i stick it in enhancements ;)

**Comment by parsimony** [comment]
This bug is fixed and availabe in RC 3.0.
