### ISSUE TITLE
Cross modules tables

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#20]
Hi ! 

What if I need to have tables commons to all my modules (with modules dependancy) ?

**Comment by parsimony** [comment]
What would be the aim(use) of your "commoms tables" ?

You can access to any entity via `\app::getModule('myModule')->getEntity('myEntity')`

**Comment by mtancoigne** [comment]
if I have a _contacts_ module wich allows me to manage contacts, and a _project_ module to manage projects, the projects must be referenced by a contact, but I want differents modules depending on each other, so I can enable only the ones I want in different cases.

The reference have to be a foreign key, but I see no way in the designer to make foreign keys from another module table...

**Comment by parsimony** [comment]
ok, not for now, perhaps you can merge your 2 modules ? i change the status of this topic to enhancements

**Comment by mtancoigne** [comment]
Thanks for info :)

But in this case, there would be not two, but maybe five or six modules, depending on one or two others...

**Comment by parsimony** [comment]
Hi,

We just enable this freature , now you can link 2 tables between differents modules.

During the creation of your link in drag n drop, you have a box that appears in top right of your page (Link to an external module), drop the link here, then choose the table that you want to link.

![linktoanexternalmodule](https://f.cloud.github.com/assets/1277326/32565/cb1d218c-5026-11e2-9795-8a06b3296040.png)

**Comment by mtancoigne** [comment]
Good news !
I'll start my tests again ;)
