### ISSUE TITLE
Bug sur l'ajout d'image

### ISSUE THREAD

**Issue by fanchlegal** [parsimony/parsimony#22]
Lorsque je souhaite importer une image dans une page, j'ai ce message qui apparait : 

{"eval":"","notification":"Redefining already defined constructor for class core\classes\upload","notificationType":"negative"}

Du coup aucune image n'arrive à se charger. Je viens de mettre la dernière version à jour, mais c'est exactement pareil.

**Comment by fanchlegal** [comment]
Je viens de passer de PHP 5.3.2 à 5.3.10 et je n'ai plus cette erreur. Si cela peut servir à d'autres personnes...

**Comment by parsimony** [comment]
Merci pour ce retour ! :+1:

**Comment by stosty** [comment]
Bonjour, un problème sur l'ajout de l'image rien n’apparaît ni dans la galerie ni dans le block de l'ajout de l'image (version PHP 5.3.16). Les fichiers ne se téléchargent pas ont dirait?

**Comment by parsimony** [comment]
Je vous répond ici https://github.com/parsimony/parsimony_cms/issues/15#issuecomment-12554893
