### ISSUE TITLE
view.php : Error in line 49 : Undefined index: title 

### ISSUE THREAD

**Issue by zinkh** [parsimony/parsimony#23]
Hi everyone, nice work btw.

Now that i managed to install parsimony without having blank screen at the end of the installation i am facing this new error:

Block #panelmodules 
Error in line 49 : Undefined index: title
File : /share/HDA_DATA/Web/parsimony/modules/admin/blocks/modules/view.php

the toolbar is not working and neither is the db designer nothing happens when i click on the links of toolbar, except for the themes and db button. and i can't create any entities when the db designer is open. I tried installing many times without success. Do you have any clue about this issue?

PS: I'm running parsimony on qnap nas btw, maybe this is the reason
PSSST: je parle français au cas où!!!

**Comment by parsimony** [comment]
Hi,
Ok, it seems Parsimony can't access to the meta data of one module, for example, for the core module : 

modules/core/module.php : 

```
namespace core;

/**
 * @title Parsimony
 * @description Module Core
 * @version 1
 * @browsers all
 * @php_version_min 5.3
 * @php_extension php_pdo_mysql,php_gd2
 * @php_settings magic_quotes_gpc:0,register_globals:0
 */

class core extends \module {
```

Even i think all is fine, can you check that ?

What was the error for the blank screen after install ?

Merci pour les compliments ;)

**Comment by zinkh** [comment]
Thanks for trying to help me, i just forgot to tell that i am not a programmer, more a "Bricoleur" ;) 
I checked the modules/core/module.php and averything is okey
i also chmod the modules folder to 777, but nothing happens, still getting the same problem.

**Comment by crackent** [comment]
Parsimony working properly in local developer WAMP (EasyPhP):

Windows XP SP3
PhP 5.4.6

But I have the same problem in remote production LAMP:

CentOS Linux 5.8
PhP 5.3.16

Error:

Block #panelmodules
Error in line 49 : Undefined index: title
File: /home/********/public_html/parsimony/modules/admin/blocks/modules/view.php

Clean and recently install.

---

Local WAMP source code:

<pre><code>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;!--[if ie]&gt;
        &lt;meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"&gt;
        &lt;script type="text/javascript"&gt;
        'article aside footer header nav section time'.replace(/\w+/g,function(n){document.createElement(n)})
        &lt;/script&gt;
        &lt;![endif]--&gt;
        &lt;meta charset="utf-8"&gt;
</code></pre>

---

Remote LAMP source code:

<pre><code>
&lt;script type="text/javascript"&gt;
    
    var CSSTHEMEPATH = "core/themes/parsidefault/desktop.css";
    var CSSPAGEPATH = "core/desktop.css";
        
    $(document).ready(function() {
        ParsimonyAdmin.initBefore();
        $(ParsimonyAdmin.currentDocument).ready(function() {
            if(!ParsimonyAdmin.isInit) ParsimonyAdmin.init();   
        });
    });
&lt;/script&gt;  
&lt;div class="subSidebar"&gt;
    &lt;div class="subSidebarOnglet handle" style="cursor: move;" draggable="true"&gt;&lt;span class="ui-icon ui-icon-arrow-4"&gt;&lt;/span&gt;&lt;/div&gt;
    &lt;div class="subSidebarOnglet revert tooltip" data-tooltip="Pin"&gt;&lt;span class="ui-icon ui-icon-seek-prev"&gt;&lt;/span&gt;&lt;/div&gt;
    &lt;div class="subSidebarOnglet openclose tooltip" data-tooltip="Show / Hide"&gt;&lt;span class="ui-icon ui-icon-circle-arrow-w"&gt;&lt;/span&gt;&lt;/div&gt;
    &lt;div class="subSidebarOnglet tooltip resizeHandle" style="cursor: w-resize;" draggable="true" data-tooltip="Resize"&gt;&lt;span class="ui-icon ui-icon-arrowthick-2-e-w ui-resizable-handle ui-resizable-e"&gt;&lt;/span&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;div class="contenttab"&gt;
            &lt;div class="mainTab panelmodules ellipsis active" rel="panelmodules"&gt;
            Modules        &lt;/div&gt;
            &lt;div class="mainTab panelblocks ellipsis " rel="panelblocks"&gt;
            Blocks        &lt;/div&gt;
        &lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;!--[if ie]&gt;
        &lt;meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"&gt;
        &lt;script type="text/javascript"&gt;
        'article aside footer header nav section time'.replace(/\w+/g,function(n){document.createElement(n)})
        &lt;/script&gt;
        &lt;![endif]--&gt;
        &lt;meta charset="utf-8"&gt;
</code></pre>

**Comment by parsimony** [comment]
Ok, i can't reproduce this bug, could you insert this code in modules/admin/blocks/modules/view.php in line 37/38 ?

`var_dump($moduleobj);exit;`

Or if you want, send me an FTP account  at contact @ parsimony-cms.com

Sorry for the response time

**Comment by crackent** [comment]
This is the result:

<pre><code> Modules
Blocks
object(core\core)#3 (5) { ["name":protected]=&gt; string(4) "core" ["title":protected]=&gt; NULL ["pages":protected]=&gt; array(6) { [6]=&gt; string(9) "@^about$@" [1]=&gt; string(9) "@^index$@" [2]=&gt; string(30) "@^category/(?(.*))$@" [3]=&gt; string(20) "@^tag/(?(.*))$@" [5]=&gt; string(49) "@^(?([0-9]{4})/?([0-9]{2})?/?([0-9]{2})?)$@" [4]=&gt; string(18) "@^(?</code></pre>
