### ISSUE TITLE
Css and JS libraries in Theme

### ISSUE THREAD

**Issue by zinkh** [parsimony/parsimony#25]
Hi guys,

I am trying to make an application using bootstrap, but i can't find where to put the necessary folders so the libraries are called in the head of the page, are these related to themes or should it be in views folder? i tried both but nothing change, could you give me a workaround to get an external css framework to work in parsimony?

Thanks in advance

**Comment by parsimony** [comment]
Hi,

You can include JS or CSS files like that :

```
<?php 
//to include js file in head tag
\app::$request->page->addJSFile(BASE_PATH . 'core/themes/mytheme/file.js');

//to include css file in head tag
\app::$request->page->addCSSFile(BASE_PATH . 'core/themes/mytheme/file.css');

//to include in the footer
\app::$request->page->addJSFile(BASE_PATH . 'core/themes/mytheme/file.js','footer'); 
?>
```

You can put this code in a block "code" for example.

**Comment by zinkh** [comment]
Ok thanks a lot, i can see the links in the header now.
BTW we can also link to external libraries using the same syntax : \app::$request->page->addJSFile("//ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools-yui-compressed.js");
don't know if it recommended though.

Now let's build my UI :+1:
