### ISSUE TITLE
Admin bug on v2

### ISSUE THREAD

**Issue by 0x6e69636f** [parsimony/parsimony#26]
![parsimobug](https://f.cloud.github.com/assets/1822081/16743/fdaebe10-484e-11e2-986c-557b9310e759.png)

Had this bug after installing v2 today.

**Comment by parsimony** [comment]
Nerver seen this bug before, please give me your server conf (os, php, apache)

**Comment by parsimony** [comment]
it seems set_include_path() function don't work as expected, but why... ?

**Comment by 0x6e69636f** [comment]
I ran it with Wamp, with no specific configuration changes, but the error might come from here. I'm gonna make some further tests
