### ISSUE TITLE
error 500 

### ISSUE THREAD

**Issue by vulcain65** [parsimony/parsimony#27]
Bonjour,

J'essaie d'installer parsimony dans un sous domaine 1and1

à priori j'ai un problème avec .htaccess

l'ordre "RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]" met le serveur en erreur 500

N'étant pas spécialiste htaccess Je ne sais quoi faire

si vous pouvez me conseiller, merci d'avance

---

AddType x-mapp-php6 .php5 .php .php3 .php4 .htm .html
AddHandler x-mapp-php6 .php5 .php
  RewriteEngine on

  #Uncomment following line and modify username if you use UserDir mod
  #RewriteBase /~myusername/
  RewriteBase /homepages/1/d141539279/htdocs/dom_parsimony/

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]

**Comment by parsimony** [comment]
Bonjour,

Essayez la déclaration  RewriteBase  comme ceci :

`RewriteBase /`

Le reste semble être bon.
