### ISSUE TITLE
PSR-0 Compliance

### ISSUE THREAD

**Issue by jena-s-lab** [parsimony/parsimony#3]
Hi,
I hate to be the dog in the bowling alley, but if you want to step up the technical legitimacy of parsimony, you'll have to refactor it, to be PSR-0 compliant.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md [EN]
https://wiki.php.net/rfc/splclassloader [EN]
http://blog.mageekbox.net/?post/2012/06/19/%C3%80-propos-de-PSR-0%2C-PSR-1-et-PSR-2 [FR]

This project is pretty cool, though, long live Parsimony !

**Comment by parsimony** [comment]
Hi,

We thank you for your advice and we think about it.

Thanks for the compliments
