### ISSUE TITLE
Deleting a line in a database

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#30]
I noticed there is no Delete mode in Content -> [TABLE] 
Would be great to be able to delete a line here.

I'll post a pull request if i manage to do it myself.
Any help would be appreciated.

![issue1](https://f.cloud.github.com/assets/2841495/103799/9c45bd3c-696d-11e2-99db-171d29426e9c.png)

**Comment by remisarrailh** [comment]
On reflection, This makes more sense to put it here

/modules/core/classes/entity.php
L413-414m

``` php
$html .= '<div style="position:absolute;right:3px;top:3px;"><input type="submit" name="update" value="' . t('Update', FALSE) . '">';
$html .= '<input type="submit" name="delete" value="' . t('Delete', FALSE) . '">';
```

![issue2](https://f.cloud.github.com/assets/2841495/104012/022b00de-6974-11e2-839d-810eb046161d.png)

**Comment by remisarrailh** [comment]
Ok I missed an opportunity to shut my mouth, i just forget to give me the permission to delete lines.

My bad.
![issue3](https://f.cloud.github.com/assets/2841495/104047/cc5131e8-6975-11e2-97c1-8050f021e5c6.png)

**Comment by parsimony** [comment]
Hi,
No problem, maybe we should put these rights by default.
Thanks for sharing your experience in github :+1:
