### ISSUE TITLE
Separate labels from inputs in FormAdd Block

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#31]
I have a hard time to design Form Add Block because the labels are attached to the fields.

``` php
<?php echo $entity->nom->formAdd(); ?>
//generate this html code
```

``` html
<div class="placeholder">
<label for="insert_nom">nom</label>
<input type="text" autocomplete="off" name="nom" id="insert_nom" class="nom" value="" pattern=".*" required />
 </div>
```

I want to do something like this:

``` html
<div class="placeholder">
<label for="insert_nom">nom</label><br>
<input type="text" autocomplete="off" name="nom" id="insert_nom" class="nom" value="" pattern=".*" required />
</div>
```

![issue4](https://f.cloud.github.com/assets/2841495/106763/b4302048-6a0a-11e2-89ba-9c1669af29ea.png)

What the best way to do an newline ?

**Comment by parsimony** [comment]
Hi,

You can just put `display:block` on label in your CSS?

**Comment by parsimony** [comment]
If you want to go faster you can use this shortcut

![Capture](https://f.cloud.github.com/assets/1277326/106806/595eaa92-6a0d-11e2-869f-d0680139549e.PNG)

**Comment by remisarrailh** [comment]
Thanks! Works great.

I noticed that you could put html code in the label fields in DbDesigner 
For exemple:
![issue5](https://f.cloud.github.com/assets/2841495/106809/82f18316-6a0d-11e2-8ace-7226a20e3ee5.png)
Will put an newline.

Really a bad way to do this but interesting to know.
