### ISSUE TITLE
Problème de connection

### ISSUE THREAD

**Issue by Blongo** [parsimony/parsimony#32]
Bonjour,
je n'arrive pas à me connecter après avoir finaliser l'installation. J'ai pourtant bien vérifier l'identifiant et le mot de passe, il n'y a pas d'erreur de ce côté là. De plus la fonction mot de passe oublié ne m'envoi rien. J'ai essayé de réinstaller mais cela n'a rien changé.
J'ai aussi essayé de changer des valeurs dans la base de donnée sur la table user mais aucunes de mes tentatives n'a été fructueuse.
Je suis a court d'idées alors si c'était possible d'avoir un petit coup de main, ça serait sympa ;)

**Comment by remisarrailh** [comment]
Lorsque tu essayes de te connecter tu as une page blanche ou un message d'erreur?

**Comment by Blongo** [comment]
J'ai un message d'erreur : "Le nom d'utilisateur ou le mot de passe que vous avez saisi est incorrect"

**Comment by remisarrailh** [comment]
Donc c'est pas un problème au niveau de la base de données, tu utilises bien l'identifiant et pas l'adresse email?

**Comment by parsimony** [comment]
Bonjour,
pour l'envoi du mot de passe, il faut que les paramètres SMTP soient configurés, ce qui n'est pas souvent le cas pour un serveur en local.
Comme le dis @maditnerd, utilisez-vous bien l'identifiant/mdp entré lors de l'installation ?

Sinon, vous ne pouvez pas changer le mdp directement dans la base de donné puisque celui-ci est un sha1 du mdp + grain de sel.

Merci de nous tenir au courant.

**Comment by Blongo** [comment]
Merci beaucoup pour vos réponses,
j'utilise bien l'identifiant et pas l'adresse mail ; entré lors de l'installation. 
Mon serveur est local et effectivement les paramètres SMTP ne sont pas configurés donc maintenant je vois pour l'envoi de mot de passe.

**Comment by remisarrailh** [comment]
Si tu rajoutes un

``` Php
echo $newPass;
```

A la ligne 152 de /modules/core/classes/user.php, tu verras le nouveau mot de passe s'afficher.

``` Php
\app::getModule('core')->getEntity('user')->where('mail = :mail')->update(array('pass' => $newPass, 'mail' => $userMail));
echo $newPass;
$password = $newPass;
```

Je pense pas que ça soit une solution au vrai problème, mais ça peut te débloquer temporairement

Evidemment n'oublie pas de l'enlever après!

**Comment by Blongo** [comment]
J'ai essayé ta proposition mais ça ne m'a pas débloqué. J'ai vérifier dans la BDD, il y a bien changement de mot de passe mais je ne peux pas me connecter avec le nouveau pour autant.

**Comment by parsimony** [comment]
Le mot de passe que vous voyez en base de donnée est crypté vous ne pourrez donc pas vous connecter en le copi/collant, comme dit plus haut, c'est un sha1 du mot de passe + grain de sel.

Pouvez vous essayer de supprimer la BDD et de réinstaller Parsimony ?

Quel est votre configuration serveur ?

**Comment by Blongo** [comment]
J'ai supprimé la BDD et réinstaller Parsimony et ça marche ! Je vois vraiment pas d'où venais le problème, peut être une erreur à l'installation. En tout cas merci beaucoup pour le soutient, je vais suivre ce projet qui m'a l'air très intéressant ;)

**Comment by parsimony** [comment]
Très bien,
Merci à toi d'avoir partagé ton expérience.
