### ISSUE TITLE
FormAdd Submit button action

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#33]
I understand that when you clicked on the submit button in FormAdd, an action is triggered
by name="add" but i can't manage to find the function who is triggered.

``` php
$html .= "\t".'<input type="submit" value="<?php echo t(\'Save\', FALSE); ?>" name="add" class="submit">'.PHP_EOL;
```

**Comment by parsimony** [comment]
This action is triggered in the view file of formAdd :

https://github.com/parsimony/parsimony_cms/blob/master/modules/core/blocks/formadd/view.php

**Comment by remisarrailh** [comment]
Thanks!
