### ISSUE TITLE
Ajax navigation crashed my back-office

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#36]
I noticed ajax navigation block my back-office everytime I activate it.

I'll try to investigated this.
## Details

The server is on port 4343, on a subdomain
http://subdomain.domain.fr:4343
## Javascript Console error

Uncaught TypeError: undefined is not a function 8e95b3f035484a12622f46ba81c89775.js:279
Uncaught ReferenceError: Color is not defined :4343/#:764
Uncaught TypeError: Cannot call method 'setPlugin' of undefined 89f02e5e87f5dcc0df30aa6312776b71.js:956
Uncaught TypeError: Cannot call method 'initBefore' of undefined 
## Javascripts

https://gist.github.com/4690773#file-89f02e5e87f5dcc0df30aa6312776b71-js

**Comment by parsimony** [comment]
Ok i found the error.
The concatFiles method of page class should split JS scripts to avoid `}function` .

Note : this functionality works only if you are logout.

**Comment by parsimony** [comment]
commit : https://github.com/parsimony/parsimony_cms/commit/2dafe070410a1bb65d078b5e774716ad98396946

**Comment by remisarrailh** [comment]
Thanks, It works great now!
