### ISSUE TITLE
2.4.1 Parsimony install - "Your database connection settings are not valid"

### ISSUE THREAD

**Issue by albert0346** [parsimony/parsimony#37]
Hi,

I deleted Parsimony 2.3 from my XAMPP-server, deleted the tables of my database and tried to install 2.4.1. But then I got the error message "Your database connection settings are not valid". Then I deleted the localhost cookey, deleted my database, created it again - but it did not help.

Please help.

Albert

**Comment by remisarrailh** [comment]
This message is triggered when :
- Database IP is not valid
- Database name is not valid
- Port is not valid
- user is not valid
- password is not valid

(L430 install.php)

I tried to install it with XAMPP (windows) and i had no issue, please verify this
- Are you sure you have create a database before installation and that you entered the good name?
- Did you add a password to your mySQL root user? (I didn't tried it with a password)
- Are you using the root user of mySQL or did you create a new one ?

**Comment by remisarrailh** [comment]
You can also see the connection error if you had this:

``` PHP
  echo $ex;
```

L442 of install.php

``` PHP
 } catch (PDOException $ex) {
                    echo $ex;
                    $connect = FALSE;
                }
```

**Comment by albert0346** [comment]
Sorry, I used the wrong password. Thanks nevertheless.

Albert

**Comment by remisarrailh** [comment]
Thank you for putting your finger on a possible improvement of the installer.
Feel free to submit questions, suggestions or bug reports.
