### ISSUE TITLE
Database Error Notifications

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#38]
I modified install.php to manage database error notification (with translation)

https://gist.github.com/4701642/revisions

You can download it here:
https://gist.github.com/raw/4701642/52581b02f69cf7941ca4c1d5aea9b39686fd6f14/install.php

**Comment by parsimony** [comment]
Thanks  for your suggestion, i just commit this improvement https://github.com/parsimony/parsimony_cms/commit/3bf1b38ea9683e5ce1c20de49a250ed246768de9 :+1:
