### ISSUE TITLE
Step 3 Install, database's user not verified if root password entered.

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#39]
If you enter a bad user and use the root password, you can still continue the installation.

![usernotverified](https://f.cloud.github.com/assets/2841495/121841/a6bd3196-6e04-11e2-8d21-7780663b061b.gif)

**Comment by parsimony** [comment]
I can't reproduce this bug.

My test :
- Server  : localhost
- Port Server :3306
- Database Name :parsimony
- User Name : dfgfdhdf
- Password : (blank)

**Comment by remisarrailh** [comment]
Me, either in the end , i don't know what happened.
It was on a xampp server on windows

Let's say the god of random was not on my side this day. ^^
