### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#4]
Hi !

I tried to install Parsimony on a xampp server (win XP) at work, and everything went good. Back home, I tried to launch the installer on my linux OS, but every folder has a 700 permission (reading only from owner) and files are 644 mod.

So, wich files/folder should be readable, writeable, and so... ?

If I had a list with the right permissions, I can make the shell script to batch do this...

Cheers :)

**Comment by parsimony** [comment]
Hi,

Which files/folder should be readable, writeable, and so... in Parsimony ?

Read / write :
- /index.php 
- /config.php 
- /install.php 
- /modules/ and subdirectories 
- /profiles/ and subdirectories 
- /cache/ and subdirectories 

Read
- /lib/ and subdirectories 

Thank you for your question :)

**Comment by mtancoigne** [comment]
Ok, thank you :)

I'll do the script tonight.

**Comment by parsimony** [comment]
If done, can you share it here ?

thank you in advance

**Comment by sahlie1985** [comment]
merci de ne plus envoyer de message

**Comment by mtancoigne** [comment]
Sure, i'll update my fork :)

@sahlie1985 :
Si tu ne veux plus recevoir de message de ce projet, désinscrits toi des informations (bouton "unwatch" en haut de page.)

**Comment by mtancoigne** [comment]
The script is available :)
https://github.com/mtancoigne/parsimony_cms/blob/master/unix_prepare_install.sh

**Comment by parsimony** [comment]
Thanks you very much for help :+1:
