### ISSUE TITLE
Accented Characters in Date of lastposts not shown correctly

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#40]
![mysql](https://f.cloud.github.com/assets/2841495/127362/6c9a277e-6f96-11e2-8848-4abe56e2dc3f.png)

I solved it by adding (utf8_encode):

``` PHP
<div class="itemprop publicationGMT"><?php echo utf8_encode(strftime('%b %d %Y', strtotime($line->publicationGMT))); ?></div>
```

source : http://stackoverflow.com/questions/8993971/php-strftime-french-characters

**Comment by parsimony** [comment]
It's fixed. Thanks for sharing !  :+1:
