### ISSUE TITLE
Block Query (hidden) bug

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#42]
When you create a Query block with an hidden field and you go to Result.
An error is display (and you can't save the query) :

```
{"notification":"Call to undefined method core\\fields\\field_ident::setVisibility() in \/var\/www\/modules\/core\/classes\/view.php in line 179","notificationType":"negative"}
```

https://github.com/parsimony/parsimony_cms/blob/master/modules/core/classes/view.php#L179
This line use : setVisibility() which seems to have been deleted in this commit:

https://github.com/parsimony/parsimony_cms/commit/2febf9c643136d354b450aa9c8308abdaf85ac93#L2R165

**Comment by parsimony** [comment]
It's a known issue, if you add the id_ of your table, it should work, but we will fix that asap.

**Comment by parsimony** [comment]
Ok,  that was just an oversight : https://github.com/parsimony/parsimony_cms/commit/89a90043236b0ef12ff275f80117f30a358aa7a8
