### ISSUE TITLE
Search features

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#43]
## I'm working on a search feature for parsimony.

![searchquery](https://f.cloud.github.com/assets/2841495/151404/05469782-7578-11e2-803b-197bf63d4203.png)

Any advice is welcome , anyway I will tried to do this by myself.

**Comment by parsimony** [comment]
Ok you can enable filter in you query block like that:
![Capturefilter](https://f.cloud.github.com/assets/1277326/152555/2045b948-75cb-11e2-833a-d5e42e39fc65.PNG)

This will add `<?php echo $this->getFilters(); ?>` in your view

![Capturefilterresult](https://f.cloud.github.com/assets/1277326/152566/9cd60cf6-75cb-11e2-88eb-4ef961ec1fbf.PNG)

and that's it :)

If you have an error to save the view after that, check this last commit https://github.com/parsimony/parsimony_cms/commit/9803ff9f60d4ef6edbbc08bd6b033ea723f040ab

If you want to do that in ajax, say to me.

**Comment by parsimony** [comment]
@maditnerd Did you find this answer appropriate?

**Comment by remisarrailh** [comment]
Didn't had time to test it sadly :-(

[OFF TOPIC]
I'm working on others projects, mainly on the Raspberry PI actually, (http://forum.snootlab.com/viewtopic.php?f=46&t=767) , i try to make a cheap (the cheapest ?) and easy way to create connected object, (movement detector, sensors, power outlet...)
I have make great progress, and the tutorial is on the way (power outlet already working great). I still need an web interface to control all this and I think parsimony could be a good candidate.

I need the search features for another project that I had in mind and thanks to parsimony, i was able to easily make (without you it would have rot in my test server...), right now is in alpha state.
It's an online drum machine based on soundcloud and his javascript API. I can add loop easily by adding the data in the database directly in the admin interface and in the future version, directly on the front-end.
You can test it on http://www.patterncloud.net (there is only one loop)

Which I had more time (and i was paid lol).
[OFF TOPIC]

Anyway i will test it when i can! Thanks for taking your time to answer my questions and to have create parsimony!

**Comment by parsimony** [comment]
Sorry for the delay.

[OFF TOPIC]
We like the projects that you realize !
[OFF TOPIC]

Thanks for your support !
