### ISSUE TITLE
FancyBox doesn't work

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#45]
When you create an image, and check the fancybox option, it doesn't work

It seems that the code lack the script to initialize and configure fancybox.
As explain in the part 5 of the how to of fancybox:
http://fancybox.net/howto
## How to fix it

/modules/core/images/view.php
And added at line 31 https://github.com/parsimony/parsimony_cms/blob/master/modules/core/blocks/image/view.php#L31

``` PHP
\app::$request->page->addJSFile(BASE_PATH . 'lib/fancybox/fancybox_setting.js');
```

Then create a file in /lib/fancybox/fancybox_setting.js with

``` JS
$(document).ready(function() {
    /* This is basic - uses default settings */
    $(".fancybox").fancybox();  
});
```
## Another bug

Jquery_fancybox have a compatibility issue with Jquery 1.9
http://stackoverflow.com/a/14344290

As a result it throw an javascript error
Uncaught TypeError: Cannot read property 'msie' of undefined

To fix this
Change l29 of jquery.fancybox-1.3.4.js
https://github.com/parsimony/parsimony_cms/blob/master/lib/fancybox/jquery.fancybox-1.3.4.js#L29

With this

``` JS
isIE6 = navigator.userAgent.match(/msie/i) && navigator.userAgent.match(/6/) && !window.XMLHttpRequest,
```

**Comment by parsimony** [comment]
Thanks for explaining ! https://github.com/parsimony/parsimony_cms/commit/de873a3150751d87f9ce6cf947d69309719cbc21
