### ISSUE TITLE
Installation Step3: Impossible de se connecter au serveur MySQL

### ISSUE THREAD

**Issue by vkoleman** [parsimony/parsimony#46]
I am trying to install Parsimony 2.5 on a Mac 10.7.5 with Apache 2.2.22 /MySQL 5.6.11 /Php 5.3.15
With phpMyAdmin, I can connect to my sql server local:3306 (php extension sqli) , where I created a parsimony database as root@localhost 
I get "Impossible de se connecter au serveur MySQL" error with:
Server: localhost
Port: 3306
DB: parsimony
User: root (or an other user created via phpMyAdmin)
Password: the corresponding password

Thanks

**Comment by remisarrailh** [comment]
Hi vkoleman!
This error is display when mysql throw an error 2002.

The official documentation say about this issue:
http://dev.mysql.com/doc/refman/5.0/en/can-not-connect-to-server.html

> The error (2002) Can't connect to ... normally means that 
> - there is no MySQL server running on the system 
> - that you are using an incorrect Unix socket file name 
> - you use an incorrect TCP/IP port number when trying to connect to the server.
>   You should also check that the TCP/IP port you are using has not been blocked by a firewall or port blocking >service. 

As you can connect to your database with PhpMyAdmin we can safely say that MySQL is running and the port is correct and not blocked.

The problem must be the socket file.
http://en.wikipedia.org/wiki/Unix_file_types#Socket

On Mac OSX, the socket file are created on **/tmp/mysqld.sock** whereas on linux, it is created on **/var/run/mysqld/mysqld.sock**
http://dev.mysql.com/doc/refman/5.0/en/macosx-installation.html

You can see where MySQL created the file with this command:
`mysqladmin variables -p |grep "sock"`

If mysqld.sock is in tmp you should try to do this
**Edit /etc/php.ini, and replace the occurrences of /var/mysql/mysql.sock with /tmp/mysql.sock**

I hope it will help you!

**Comment by vkoleman** [comment]
Hi Rémi,

Thanks a lot. I fixed my /etc/php.ini file, rebooted, and I was able to
move forward to the step4 of the installation
Regards,

véronique koleman

2013/4/25 Sarrailh Rémi notifications@github.com

**Comment by remisarrailh** [comment]
You're welcome ^^
Feel free to ask questions, and have fun with parsimony!

**Comment by parsimony** [comment]
@maditnerd :+1:
