### ISSUE TITLE
no CSS and images after install

### ISSUE THREAD

**Issue by vkoleman** [parsimony/parsimony#47]
Hello,

I am still trying to install Parsimony 2.5 on a Mac 10.7.5 with Apache 2.2.22 /MySQL 5.6.11 /Php 5.3.15

I have some kind go mix of:
#8 Blank screen after install
#12 "/blabla/connect" Not Found after install

mod_rewrite is active as I get logs in /var/log/apache2/rewrite.log

in the index.php, I added:
echo realpath($_SERVER['DOCUMENT_ROOT']);
echo "<br>";
echo __DIR__;
and got:
/Library/WebServer/Documents
/Library/WebServer/Documents/cms_parsimony

in the config.php:
$config['BASE_PATH'] = '/';
$config['DOCUMENT_ROOT'] = **DIR**;

I changed the permissions of /Library/WebServer/Documents/cms_parsimony to (o+w) (but not recursively)

the /Library/WebServer/Documents/.htaccess is:
RewriteEngine On
I tryed to add:
RewriteBase /cms_parsimony  -> no change

the /Library/WebServer/Documents/cms_parsimony/.htaccess is:
RewriteEngine On
I tryed to add:
RewriteBase /cms_parsimony  -> no change

Pb1:
http://localhost/cms_parsimony/connect NotFound

Pb2:
http://localhost/cms_parsimony/ doesn't see the stylesheets and images

Pb3: 
using http://localhost/cms_parsimony/?parsiurl=connect 
the connecting page was displayed with CSS and I was able to connect once 

Pb4: now that I am connected without CSS and images, I don't see how to logout
and none of the links work
same behaviour with http://localhost/cms_parsimony/index.php
                        and  http://localhost/cms_parsimony/

Thanks

**Comment by remisarrailh** [comment]
This is clearly an mod_rewrite problem.

If mod_rewrite is active then the issue could be two things:

You must have at the root of the website (/Library/WebServer/Documents/cms_parsimony/) an .htaccess with

```
<IfModule mod_rewrite.c>
  RewriteEngine on

  #Uncomment following line and modify username if you use UserDir mod
  #RewriteBase /~myusername/

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]
</IfModule>
```

And in your apache configuration 

```
AllowOverride All
```

or apache will not read the .htaccess
http://chibimagic.wordpress.com/2009/02/27/apache-htaccess-mac-os-x/

Source:
http://parsimonycms.blogspot.fr/2013/02/impossible-dacceder-connect.html

**Comment by vkoleman** [comment]
Hello Rémi,

I tried to fixe and still get the same problem.

below is the rewrite log:

::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2692044a0/initial](2) [perdir
/Library/WebServer/Documents/cms_parsimony/] rewrite 'connect' ->
'index.php?parsiurl=connect'
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2692044a0/initial](3) split
uri=index.php?parsiurl=connect -> uri=index.php, args=parsiurl=connect
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2692044a0/initial](3) [perdir
/Library/WebServer/Documents/cms_parsimony/] add per-dir prefix: index.php
-> /Library/WebServer/Documents/cms_parsimony/index.php
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2692044a0/initial](2) [perdir
/Library/WebServer/Documents/cms_parsimony/] strip document_root prefix:
/Library/WebServer/Documents/cms_parsimony/index.php ->
/cms_parsimony/index.php
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2692044a0/initial](1) [perdir
/Library/WebServer/Documents/cms_parsimony/] internal redirect with
/cms_parsimony/index.php [INTERNAL REDIRECT]
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2691e0d40/initial/redir#1](3) [perdir
/Library/WebServer/Documents/cms_parsimony/] strip per-dir prefix:
/Library/WebServer/Documents/cms_parsimony/index.php -> index.php
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2691e0d40/initial/redir#1](3) [perdir
/Library/WebServer/Documents/cms_parsimony/] applying pattern '^(.*)$' to
uri 'index.php'
::1 - - [26/Apr/2013:14:49:34 +0200]
[localhost/sid#7fc269022b08][rid#7fc2691e0d40/initial/redir#1](1) [perdir
/Library/WebServer/Documents/cms_parsimony/] pass through
/Library/WebServer/Documents/cms_parsimony/index.php

The .htaccess files are now:

cat .htaccess
RewriteEngine On
RewriteBase /cms_parsimony

cat cms_parsimony/.htaccess
<IfModule mod_rewrite.c>
  RewriteEngine on

  #Uncomment following line and modify username if you use UserDir mod
  #RewriteBase /~myusername/

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]
</IfModule>

Sorry,

véronique koleman

2013/4/26 Sarrailh Rémi notifications@github.com

**Comment by vkoleman** [comment]
After reboot (session exited) 

http://localhost/cms_parsimony/connect  display the connect menu with almost all css elements except one image
http://localhost/cms_parsimony/  display the website page with no css and no images

It is better, but not totally fixed

**Comment by vkoleman** [comment]
It is working now.

The localhost/cms_parsimony/.htaccess file is:
<IfModule mod_rewrite.c>
  RewriteEngine on  
  RewriteBase /cms_parsimony
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]
</IfModule>

and
The localhost/cms_parsimony/index.php file is updated with:
$config['BASE_PATH'] = '/cms_parsimony/';

Thanks for your help and your blog.

véronique koleman
