### ISSUE TITLE
[BUG] Unable to save database changes

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#5]
Hello again,

Back to windows (WIN 7 64bits) with Xampp1.8 (apache2.4, PHP5.4, Mysql5.5).
I created my first table for a test module, with only two fields, and when I click on the "save" button, I got this error :

> Le nouveau modèle de données a été sauvé{"notification":"Call to a member function getAllRights() on a non-object in C:\xampp\htdocs\parsimony\modules\admin\module.php in line 1259","notificationType":"negative"}

And I'm stuck here...

[EDIT] If I close/reopen the DB Designer, there's no more table in it for my module, and if I try to re-create the table, I automatically fall back to the core module DB Design.

**Comment by parsimony** [comment]
Hi,

First, thank you for your question !
This is related to server configuration problems : https://github.com/parsimony/parsimony_cms/issues/4
There is a change available on github to install Parsimony (install.php)

I hope that this answers your question :)

**Comment by mtancoigne** [comment]
Again :)
I don't think that the DB saving problem are related to file permissions, because files are created in the module folder for the new tables, but the database isn't changed at all. So I think the problem comes from somewhere else.

What about creating a forum on you website, so the community could help :P ??

A more detailed post about the problems I encountered has been created here : http://forum.korben.info/topic/12980-parsimony-les-bugs/ (in FR)

**Comment by parsimony** [comment]
Ok it was regression bug, it's resolved ;)

A forum is in creation, we will keep you informed on twitter https://twitter.com/parsimony_cms

**Comment by mtancoigne** [comment]
Great !
