### ISSUE TITLE
The save changes bar doesn't appear

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#52]
In 3.0RC version, i don't see the save changes bar anymore when I modify a WYSIWYG block.

Anyone has the same problem?

**Comment by parsimony** [comment]
Thank you for your feed-back!

Unit tests are in progress.
Minor modifications were made before the actual release of version 3.0.

These changes may cause some bugs that will be corrected by the unit tests.

**Comment by remisarrailh** [comment]
I tried with the new version (June 27 2013) and now it works great.
Thanks!

**Comment by parsimony** [comment]
Hope you feel fine
Thanks for your feedback

Unit tests are always in progress.We'll publish them soon. V3.0 is coming soon.
