### ISSUE TITLE
Impossible de se connecter post install

### ISSUE THREAD

**Issue by happytodev** [parsimony/parsimony#54]
Hello la communauté Parsimony,

J'ai vu qu'il y avait déjà un bug de ce type et la résolution passait par la réinstallation de Parsimony.

Donc, j'ai installé Parsimony en local via Wamp.

Première chose l'install débouche après un très long temps de "réflexion" sur une page blanche. Quand je saisie mon url définie par un virtual host (parsimony.dev) je retombe sur l'install depuis le début.

Bref après 2 ou 3 tentatives d'install, j'arrive sur la page /connect, je saisis mes identifiants / mot de passe (pas l'adresse mail mais bien l'identifiant) mais je reçois le message d'erreur (pas une page blanche) : "Le nom d'utilisateur ou le mot de passe que vous avez saisi est incorrect"

J'ai supprimé la base de données et les fichiers et refaits 2 ou 3 fois l'install (sous Opera et Firefox) mais rien à faire.

J'aimerai donc que vous me donniez quelques astuces pour m'en sortir ;)

PHP 5.4.12
MySQL : 5.6.12
Apache : 2.4.4
OS : Seven

Merci d'avance.
++
Fred

**Comment by parsimony** [comment]
Bonjour,

Selon nos tests, ce serait une mauvaise configuration du serveur SMTP dans le PHP.ini.
En effet, lors de l'installation, Parsimony envoi un mail de confirmation de création de compte admin, et il utilise les configurations par défaut du PHP.ini, si celles-ci ne sont pas (ou mal) configurées, l'envoi du mail n'aboutit pas, met trop de temps et fait arrêter le script.

Nous cherchons une solution, pour qu'en cas d’absence (ou de mauvaise) de configuration mail, l'installation puisse aboutir.

Un simple rafraîchissent de la page blanche peux suffire pour utiliser Parsimony, sans le réinstaller.

Pour confirmer notre hypothèse, pouvez-vous tester l'installation avec une nouvelle configuration SMTP du PHP.ini ?

Merci de votre retour !

**Comment by happytodev** [comment]
Bonsoir,

En effet, il a suffit de mettre localhost comme host SMTP dans mon php.ini de mon WAMP et cela a fonctionné.
Merci pour votre support.

Cordialement,
Frédéric Blanc
