### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by mageex** [parsimony/parsimony#55]
hello guys

i have an error like the following lines below

Code: 8192
Fichier : Unknown
En ligne : 0
Message : Directive 'register_long_arrays' is deprecated in PHP 5.3 and greater

can someone help please i'm not very familiar with all this language

regards

**Comment by parsimony** [comment]
Hi,
It appears to be a php.ini issue.
Can you check these directives ? : 

```
magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
```

**Comment by mageex** [comment]
Hi

yes its already off for those directives

**Comment by parsimony** [comment]
Check also : 

```
register_globals = Off
register_long_arrays = Off
```

?

**Comment by mageex** [comment]
its also done,

**Comment by parsimony** [comment]
What version of php do you use?
What is your web development environment ? Are you using Apache, XAMPP, WAMPSERVER...?
