### ISSUE TITLE
Insertion form overflow bug

### ISSUE THREAD

**Issue by 0x6e69636f** [parsimony/parsimony#56]
When you have a lot of fields in a table, the form shown when you click "add" to insert data into it doesn't display them all, and you can't scroll to make them visible  : 
![insert_form](https://f.cloud.github.com/assets/1822081/1558213/10ee7b74-4f73-11e3-84e0-14c48d67b832.png)

**Comment by parsimony** [comment]
It's fixed now, thank you :+1:
