### ISSUE TITLE
Fresh install preview/edit/design mismatch

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#59]
Just doing a fresh install I noticed a mismatch between preview/edit/design, on edit the header collapse with the sub header.
![Uploading parsimony-edit.png . . .]()
![Uploading parsimony-design-preview.png . . .]()

**Comment by mingodad** [comment]
![parsimony-design-preview](https://f.cloud.github.com/assets/462618/2086583/293c852e-8e5a-11e3-9c44-1d628daece09.png)
![parsimony-edit](https://f.cloud.github.com/assets/462618/2086585/335da060-8e5a-11e3-8d11-b065c8ff1e94.png)

**Comment by mingodad** [comment]
Another issue is when selecting the header and then trying to change it's color when clicked on a color it selects the image behind it.
![parsimony-color-issue](https://f.cloud.github.com/assets/462618/2086619/faf096be-8e5a-11e3-8309-a494e24840f9.png)

**Comment by mingodad** [comment]
Also when trying to change a color through css it seems to create a css entry but it does not apply to selected element.
![parsimony-css-color-issue](https://f.cloud.github.com/assets/462618/2086636/a90ab11c-8e5b-11e3-8868-bae79435f56c.png)

**Comment by mingodad** [comment]
Also when in design mode and selecting an element we have the visual css settings available but if we switch to edit mode and switch back to design mode we do not have visual css anymore.
![parsimony-visual-css-issue-1](https://f.cloud.github.com/assets/462618/2086682/c0f7fb4e-8e5c-11e3-9970-6492a4a6eea8.png)
![parsimony-visual-css-issue-2](https://f.cloud.github.com/assets/462618/2086683/c58f6322-8e5c-11e3-9532-51653039b66a.png)

**Comment by mingodad** [comment]
I noticed that when switching from design to edit and back to design the visual css do not appear when selecting elements clicking on themselves but if we select then through the tree view the visual css do appear again.

**Comment by mingodad** [comment]
Also when setting a measure unit it reflects the setting instantly but when switch to code the measure unit is lost.
![parsimony-visual-css-issue-measure-unit-1](https://f.cloud.github.com/assets/462618/2086778/cf71c0ae-8e5e-11e3-951a-6ed0ea04a9df.png)
![parsimony-visual-css-issue-measure-unit-2](https://f.cloud.github.com/assets/462618/2086779/d1fe59fe-8e5e-11e3-88b7-2083f0facb41.png)

Looking again on this problem I found that it seems to only happen when the value we are changing is located at the first line on the code window. if we remove the first line on the code window then the next value that now is at the first line will not be updated by changing it's value through the visual css form.

Changing the regular expressions on block.js fix the problems.

/\* We check if property is already set, must manage with : min-width and width props like _/
            if (oldCssText.match(new RegExp("[^a-z-]_" + this.dataset.css + "[\s ]?:")) != null) {
                if (this.value.length > 0) {
                    newCssText = oldCssText.replace(new RegExp("([^a-z-]_)(" + this.dataset.css + "[^;]_)"), "$1" + this.dataset.css + ": " + this.value);
                    console.log(newCssText);
                } else { /\* if there is no value we delete property _/
                    newCssText = oldCssText.replace(new RegExp("([^a-z-]_)" + this.dataset.css + "[^;]*[;]?"), "$1");
                }
            }

...

blockAdminCSS.prototype.getLastCSS = function(filePath, ident) {
    var code = "";
    if (typeof ParsimonyAdmin.CSSValuesChanges[filePath] != "undefined") {
        if (typeof ParsimonyAdmin.CSSValuesChanges[filePath][ident] != "undefined") {
            code = ParsimonyAdmin.CSSValuesChanges[filePath][ident].value.trim();
            return code; //if we already cleaned up do not try to go further
        }
    }

**Comment by mingodad** [comment]
Also when clicking on visual css reinit icon we loose visual css settings.
![parsimony-visual-css-issue-3](https://f.cloud.github.com/assets/462618/2086825/91ef92b4-8e5f-11e3-9b47-2caac33817b7.png)

**Comment by mingodad** [comment]
When clicking the css reinit icon and loosing the visual css settings even if we try to select an element through the DOM tree the visual css settings do not come back.

**Comment by mingodad** [comment]
Also in edit mode when click to select the "About" header/column we have a javascript error:
Uncaught TypeError: Cannot call method 'onClick' of undefined jsconcat_165db2c166e0602160d3e175b5e0f208.js:133
(anonymous function) jsconcat_165db2c166e0602160d3e175b5e0f208.js:133
x.event.dispatch jquery.js:5116
v.handle
![parsimony-onclick-issue](https://f.cloud.github.com/assets/462618/2086887/1458334a-8e61-11e3-8d1f-9920f32b9cad.png)

This error happen because the this.dataset.mode has a value of "blockwysiwyg" but the pasiEdit.tools array do not have that entry ("blockwysiwyg").

Changing the parsiEdit.init function to:

var tool = parsiEdit.tools[this.dataset.mode];
if(tool) tool.onClick(this);

Prevents the onclick error but I'm not sure if it's the best solution.

**Comment by mingodad** [comment]
It seems that when it enters the edit mode it do not switch to other modes anymore because switching to preview mode still allow select and edit elements.

With firefox when switching between modes on edit mode we get an alert box with "Error" as a message.

**Comment by parsimony** [comment]
Thanks for your feedbacks, we 'll check and resolve them one by one as soon as possible.

**Comment by mingodad** [comment]
Ok thanks !

Also another related issue is the save button appears inactive at the screen bottom.
![parsimony-edit-save-issue](https://f.cloud.github.com/assets/462618/2087255/5b4a321a-8e68-11e3-8d73-ae7b408b332e.png)

**Comment by parsimony** [comment]
It seems all your feedbacks have been fixed, thanks a lot
