### ISSUE TITLE
Having a decent/easy I18n/L10n using GetText

### ISSUE THREAD

**Issue by jena-s-lab** [parsimony/parsimony#6]
Hi,

It's me, again (not "super connard", but maybe close), you seem to really bother yourself with translations and all that crap…
So, may I suggest using GetText ?
http://www.php.net/manual/en/book.gettext.php
just sayin' ¬¬

**Comment by parsimony** [comment]
Hi,

Why you do think that ?

Good suggestion, but we have already test gettext, but in our sense it's not the parsimonious way (binary files .mo, .po, etc ) ;)

Thanks for your interest, u r not a  "super connard"  :)

**Comment by mtancoigne** [comment]
Allez, on se force tous à parler anglais sur un projet français !! :trollface:

**Comment by jena-th** [comment]
Comme tu veux.

Sinon concernant Gettext il y a de relativement bon outils, j'utilise POEdit, pour automatiquement extraire toutes les chaînes traduisibles et générer le .pot puis exporter les .po … Comme ça vous n'auriez plus à reporter consciencieusement chaque chaine et faire des tableaux PHP monstrueux…

Après, je comprend votre côté "it's not the parsimonious way", juste c'est très risqué de croire que vous n'oublierez aucune chaine…

**Comment by parsimony** [comment]
Alors en fait il y a une petite interface de traduction (qui s'améliorera), quand tu cliques sur un texte traduit (  <?php echo t('Bonjour');  ), ce qui permet de traduire directement en ligne sans aucun logiciel, et cela nous permet de l'enregistrer dans les fichiers locales a la volée.

Nous avions testé getText qui est assez utilisé dans d'autres solutions, mais il ne nous permettait pas cela.

Merci quand même pour ces propositions, nous allons faire plus d'articles pour expliquer chacun de nos choix .

Si tu as d'autres suggestions ce sera toujours avec plaisir :)

**Comment by jena-th** [comment]
Ho il faut vraiment qu'au lieu de lire le code je me fasse une petite install !

**Comment by mtancoigne** [comment]
oui, c'est vraiment prometteur :)
...malgrès tout... :trollface:
