### ISSUE TITLE
Unable to save any edited page on a fresh install

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#60]
Just did a fresh install and noticed that it's not possible to save any edited page, the save button appear on the page bottom in an inactive state.

To continue to evaluate/test the actual version master/head of parsimony this is a stopper.

I want to test new pages to test designs from http://webflow.com and see how it will deal with then.

Also comparing to http://www.dockphp.com/ that has the visual css settings on a floating window would be nice to implement the same on parsimony.

Another place for inspiration that I use is http://enyojs.com they have a two way edit mode for javascript on their ide "ares-ide" and interesting javascript solutions for mobile applications that we can try implement on parsimpony.

Please can you fix this "save" issue as soon as possible ?

Thanks for this great work.

**Comment by parsimony** [comment]
"Save" issue is now fixed, thanks theses ressources, we will take a look.

**Comment by mingodad** [comment]
Yes you are right we can now save, but after saving any of the three bottom columns their content disappear from screen.

**Comment by parsimony** [comment]
I don't have this behavior.. i will check in other environments.
