### ISSUE TITLE
When setting a background image it does not take in account sub folder installation

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#62]
Testing the visual css background image on a installation inside a folder the generated code for the url do not take in account it.

Actually it generates: background: url(/drop.png);
Instead of: background: url(/install_folder/drop.png) ;

**Comment by parsimony** [comment]
Ok it was a regression, it's now fixed with this commit: https://github.com/parsimony/parsimony/commit/8cb8fd57588e061bf4ca18cf6b267cd57eaf7b49
