### ISSUE TITLE
After save a page block it's content disappear

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#63]
Now we can save page blocks but after doing it and selecting another block the saved content disappear from the screen.
![parsimony-edit-save-issue-2](https://f.cloud.github.com/assets/462618/2105403/e57b301e-8f8b-11e3-9e6a-d6b34c1cb60f.png)

**Comment by parsimony** [comment]
It seems to be fixed with this commit ? https://github.com/parsimony/parsimony/commit/3c986e4b75e0a4b02f686bcf78d6aa8c265964a8

**Comment by mingodad** [comment]
Yes it is not disappearing now, thanks for fixing it.
