### ISSUE TITLE
After creating a new page fail to insert gallery block

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#64]
![parsimony-new-page-insert-block-issue](https://f.cloud.github.com/assets/462618/2105444/a7dd4516-8f8c-11e3-9956-baf513ccbe1a.png)
## Also when try to see the settings of that block we get this error:

Code: 8
File : /home/mingo/dev/php/parsimony_cms_master/modules/core/blocks/gallery/adminView.php
In line : 35
## Message : Use of undefined constant THEME - assumed 'THEME'

And then viewing the website as a visitor looses all styles.
![parsimony-loose-style-issue](https://f.cloud.github.com/assets/462618/2105460/0f6e40ea-8f8d-11e3-88bb-d266ad1b9c51.png)

**Comment by parsimony** [comment]
Yes we know this problem, we have to refactor this block as soon as possible.

**Comment by parsimony** [comment]
Issue has been fixed
