### ISSUE TITLE
After login clicking a link gives javascript error

### ISSUE THREAD

**Issue by mingodad** [parsimony/parsimony#65]
I noticed that after login we can switch modes preview/edit/design without problem but if we select another page or click a link in preview mode we get this javascript error:

Uncaught ReferenceError: parsiEdit is not defined jsconcat_b3672da6e64f532f176d28f672349bb3.js:939

And after that it's not possible to edit/design without refresh the page, also we get the same error if we try to refresh the page http://localhost/php/parsimony_cms_master/about

We also get the same error if we click on the index page and then try to switch to edit mode.

![selection_001](https://f.cloud.github.com/assets/462618/2110194/ad1551a0-8ffe-11e3-9070-0ab035b7f502.png)

**Comment by mingodad** [comment]
Investigating this issue I could see that the problem is that somehow the "parsiEdit" object is not initialized on some windows.

Adding "\app::$response->page->addJSFile('core/js/editinline.js');" to "core/blocks/wysiwyg/block.php" in function "loadExternalFiles" prevents the error message when we select the "about" page but for other pages the error persist.

**Comment by mingodad** [comment]
Looking at the requests made by the "about" page and the others I noticed that only about page includes javascript that initialize "parsEdit".

**Comment by parsimony** [comment]
Investigating too, i also notice that 'core/blocks/wysiwyg/edit.js' isn't include when this issue occur.

**Comment by parsimony** [comment]
Can you confirm it's fixed with this commit ? https://github.com/parsimony/parsimony/commit/cda80545ea7c55cb4ab67da638bb003e7c2109ff

"beforePageLoad" event was already fired when the block wysiwyg was included, so we have to bind js/css includes to "afterPageLoad", also the Wysiwyg was initialized too early

**Comment by mingodad** [comment]
Yes it's not giving any error now, again thanks for the fix.
