### ISSUE TITLE
Error in admin mode

### ISSUE THREAD

**Issue by lekrys** [parsimony/parsimony#7]
Hi i got the following message in the left panel

Block #panelmodules
Error in line 263 : Invalid argument supplied for foreach()
File : /home/www/.........../web/parsimony/modules/core/classes/module.php

Any idea ?
Thanks

**Comment by mtancoigne** [comment]
When did the error occurs ?

**Comment by lekrys** [comment]
When i am connected as admin.

**Comment by mtancoigne** [comment]
You installed Parsimony and the error comes at your fisrt login ?

**Comment by lekrys** [comment]
Yes, the first and the other ones.

**Comment by parsimony** [comment]
This pb may be caused by your web host when if they have disabled the glob() function ?

**Comment by lekrys** [comment]
Nop,the glob function is enabled. I tried a little script and it worked.

**Comment by mtancoigne** [comment]
and what's your little script, it may be interesting to post it here :)

**Comment by lekrys** [comment]
The script to verify that your hosting provider has not disabled the glob function ? just pick it from the manual :-D

 <?php
     foreach (glob("*.php") as $filename) {
       echo "$filename size " . filesize($filename) . "\n";
     }
?>

**Comment by mtancoigne** [comment]
Mouarf, j'ai cru que tu avais résolu ton pb avec un petit script... :D

**Comment by lekrys** [comment]
Hélas non,
par contre ce doit être hébergement-dépendant, j'ai installé parsimony sur une ubuntu 12.04 et pas du tout le pb en localhost.
:(

**Comment by mtancoigne** [comment]
Ben en local sur ma linux mint 13, j'ai un écran blanc après install...

**Comment by parsimony** [comment]
@lekrys Pourrais-tu insérer la ligne suivante en 263 du fichier modules/core/classes/module.php:
`echo 'modules/' . $this->name . '/model/*.php';exit;`

ce qui donnerai:

```
...
public function getModel() {
    echo 'modules/' . $this->name . '/model/*.php';exit;
    foreach (glob('modules/' . $this->name . '/model/*.php') as $filename) {
...
```

et regarder le resultat.
Si tu c'est "modules/core/model/*.php", c'est : 
- soit un problème de la fonction glob
- soit qu'il n'y pas de fichiers dans modules/core/model/...
- sinon essaye d'insérer la ligne suite au même endroit et me donner le résultat(set_include_path ne passe peut être pas sur ton hebergeur, d'ailleur qu'el est t-il ?)

`echo get_include_path();exit;`

Merci pour ton aide !

**Comment by lekrys** [comment]
1) J'avais mis un die pour afficher $this->name et effectivement on a core.
2) l'include_path donne .:./profiles/www/modules/:./modules/:./modules/core/
3) Infomaniak est l'hébergeur.

**Comment by parsimony** [comment]
Tout est bon...
Apparemment glob() aurait un comportement différent avec le safe_mode, peux tu tester, si l'hergement est sous safe_mode ?

```
if( ini_get(‘safe_mode’) ){
echo “Safe mode is on”;
}else{
echo “Safe mode is off”;
}
```

source : https://bugs.php.net/bug.php?id=28932 (fin de page)

**Comment by lekrys** [comment]
Le safe_mode est à off.

**Comment by parsimony** [comment]
ok, un

```
 die(is_file('modules/core/model/post.php'));
```

 devrait définitivement nous aider :)

**Comment by lekrys** [comment]
TRUE (1)

**Comment by parsimony** [comment]
et seulement

```
<?php
foreach (glob('modules/core/model/*.php') as $filename) {
echo "$filename size " . filesize($filename) . "\n";
}
?>
```

en dehors de Parsimony et à la racine de Parsimony?

**Comment by lekrys** [comment]
En dehors : 
parsimony/modules/core/model/category.php size 718 parsimony/modules/core/model/category_post.php size 596 parsimony/modules/core/model/comment.php size 1315 parsimony/modules/core/model/post.php size 1220 parsimony/modules/core/model/role.php size 498 parsimony/modules/core/model/tag.php size 492 parsimony/modules/core/model/tag_post.php size 546 parsimony/modules/core/model/user.php size 1351

**Comment by lekrys** [comment]
Dedans : 
modules/core/model/category.php size 718 modules/core/model/category_post.php size 596 modules/core/model/comment.php size 1315 modules/core/model/post.php size 1220 modules/core/model/role.php size 498 modules/core/model/tag.php size 492 modules/core/model/tag_post.php size 546 modules/core/model/user.php size 1351

**Comment by parsimony** [comment]
et si on rajoute l'include_path devant ?

```
set_include_path('.:./profiles/www/modules/:./modules/:./modules/core/');
```

..?

**Comment by lekrys** [comment]
Avec le set_include devant et toujours à la racine de parsimony : 
modules/core/model/category.php size 718 modules/core/model/category_post.php size 596 modules/core/model/comment.php size 1315 modules/core/model/post.php size 1220 modules/core/model/role.php size 498 modules/core/model/tag.php size 492 modules/core/model/tag_post.php size 546 modules/core/model/user.php size 1351

**Comment by parsimony** [comment]
ok merci bcp pour ton aide ! , dommage que je ne puisse pas reproduire ce bug, je ne vois pas ce qui peut clocher pour l'instant

**Comment by lekrys** [comment]
ok, je vais regarder plus sérieusement ce WE

**Comment by parsimony** [comment]
Merci encore pour ton aide :+1: 

En fait sous certains systèmes la fonction glob() renvoie false si elle ne trouve pas le path, sous d'autres ( comme indiqué dans la doc) elle renvoie un tableau vide.

Ce problème est fixé !

**Comment by Lephoenix** [comment]
Bonjour,

Est-ce que Lekrys ou Parsimony ont trouvé une solution pour ce problème toujours existant ?

Que faut-il rajouter dans module.php pour que cela fonctionne de façon normale ? (ou un autre fichier / config php)

Bien à vous,
Lephoenix

**Comment by parsimony** [comment]
Bonjour,

Vous avez l'erreur ci-dessous ? Avec une version à jour de parsimony (voir /config.php)? 

`Block #panelmodules
Error in line 263 : Invalid argument supplied for foreach()
File : /home/www/.........../web/parsimony/modules/core/classes/module.php`

**Comment by Lephoenix** [comment]
Bonjour,

Oui dernière version de Parsimony téléchargée hier sur le site officiel

et l'erreur est bien celle la

J'ai regardé ma config php.ini, le safe mod est bien sur off
Je ne retrouve pas un numéro de version dans mon config.php par contre.

**Comment by parsimony** [comment]
Le numéro de version est dans index.php, désolé (normalement 2.2).
Pourriez-vous me dire quelle est votre configuration serveur ?

**Comment by Lephoenix** [comment]
define('PARSIMONY_VERSION','2.2');

OS Serveur:      CentOS
Version d'Apache:   2.2.15
Version de PHP:     5.3.3
Version de MySQL:   5.1.66

**Comment by parsimony** [comment]
Le problème était réglé pour le module admin mais pas le module core, ce qui est maintenant fait.
Il semblerait que ce problème soit généré par la configuration PHP `open_basedir` (cf https://bugs.php.net/bug.php?id=47358)

**Comment by Lephoenix** [comment]
Super, ça fonctionne.

Juste encore un petit message sql qui apparait:

SELECT core_post.title,core_post.url,core_post.content,core_post.publicationGMT,core_user.pseudo,core_post.id_post,core_user.id_user FROM core_post inner join core_user ON core_post.author = core_user.id_user LIMIT 0,10 SELECT core_post.title,core_post.url,core_post.content,core_post.publicationGMT,core_user.pseudo,core_post.id_post,core_user.id_user FROM core_post inner join core_user ON core_post.author = core_user.id_user LIMIT 0,10

![sql](https://f.cloud.github.com/assets/3283930/71778/f942bf56-5ff6-11e2-8ab9-e6152fe5f7cc.png)

**Comment by parsimony** [comment]
Effectivement petit oubli de debug, merci ceci est corrigé .

**Comment by Lephoenix** [comment]
En tout cas, un support ultra rapide et un tout gros bravo pour ce cms :+1: 

J'ai par contre encore un petit soucis avec la dernier version, quand je me connecte à l'admin, il est splité en deux sur l'axe horizontal (voir screens).

J'ai refais une install from scratch et vidé mon cache (problème présent sur Firefox & Chrome)

Une idée?
![Part 1](https://f.cloud.github.com/assets/3283930/71950/f2921ffc-5ffc-11e2-8bf7-88b1b2bea7c9.png)
![Part 2](https://f.cloud.github.com/assets/3283930/71951/f66e2ea4-5ffc-11e2-9d84-b20c4c51e3f4.png)

**Comment by stosty** [comment]
@Lephoenix le même chez moi.

**Comment by parsimony** [comment]
Avez-vous installé une ancienne version de Parsimony ? Pourriez-vous vider les cookies pour voir ?
On vient de relancer des tests, pas de problème ici sur l'interface.
Sinon on cherchera d'autres solutions.

**Comment by Lephoenix** [comment]
J'ai refais une install from scratch et vidé mon cache + coockies (problème présent sur Firefox & Chrome).

Aussi testé avec un autre pc sur lequel je n'étais pas encore allé sur le cms.

Version téléchargée: 2.2-18-g736e2ed

Dans le doute, j'ai refais une installation sur un nouveau compte FTP + nouvelle base de donnée, mais problème identique.

**Comment by Lephoenix** [comment]
Je peux éventuellement, fournir un accès ftp / sql par email pour tester (quelques fois que je me serai planté dans l'install pourtant bien simple ou dans la configuration du serveur => moins simple ça)

**Comment by parsimony** [comment]
Oui ce serait très bien. Le compte FTP suffira. Merci par avance !
Notre mail : contact@parsimony-cms.com

**Comment by Lephoenix** [comment]
Mail envoyé

**Comment by parsimony** [comment]
Merci pour votre aide. Un problème sur glob() restait présent pour certaines configurations serveur.

**Comment by parsimony** [comment]
La mise à jour est effective sur github ! @stosty @Lephoenix

**Comment by Lephoenix** [comment]
Merci, je viens de refaire l'installation et apparemment tout fonctionne bien.

**Comment by parsimony** [comment]
Parfait !

**Comment by stosty** [comment]
Pour moi c'est bon aussi.
