### ISSUE TITLE
Blank screen after install

### ISSUE THREAD

**Issue by mtancoigne** [parsimony/parsimony#8]
Salut, c'est encore moi !

J'ai fait le script pour les changements, de permissions sur les fichiers/dossiers, et il fonctionne. Mais le fait de changer les permissions ne résous pas le problème d'écran blanc après install sous Linux. J'ai comparé les fichiers _apres installation_ entre une copie windows/xampp et linux, et j'ai pas noté de différences entre les fichiers, mis à part que sous linux il ne se passe absolument rien.

Pas d'erreur PHP, pas d'erreur Apache. 

J'ai comparé les fichiers php.ini des deux systèmes, et rien de ce côté là.

Sous Linux, j'utilise Parsimony dans mon "/home/public_html" avec le module "_userdir_" d'Apache, et y accède donc par _127.0.0.1/~mt/parsimony_.
Un changement dans le fichier **.htaccess** s'impose : `RewriteBase /~mt/parsimony`, ne serai-ce que pour lancer l'installateur.

Serait-il possible que le problème vienne de là et que Parsimony doive être lancé à partir de la racine du serveur ?
Ou qu'il vienne de la configuration d'Apache ?

(Désolé, pas le courage d'écrire ce post en anglais, et au pire, la solution se retrouvera dans la doc bilingue, ou le problème sera réglé...)

**Comment by lekrys** [comment]
J'ai eu ce problème sous linux, il fallait que le répertoire d'installation ait les permissions d'écriture (o+w) afin de permettre la création de cache.

**Comment by mtancoigne** [comment]
Yep, mais là, le cache est créé en mode 777 avec mon script, donc je pige pas...

**Comment by parsimony** [comment]
Pourrais-tu copier ce morceau de code en haut de index.php sur ton linux pour activer l'affichage des erreurs si ce n'est pas le cas ? 
Au cas où le script génère une erreur dès l'index ?
ini_set('display_errors', 1); 
ini_set('log_errors', 1); 
error_reporting(E_ALL);

**Comment by mtancoigne** [comment]
Pas de soucis, je regarde ça ce soir (mon poste linux est chez moi, et je suis au taf...)

**Comment by mtancoigne** [comment]
Donc, après modification de index.php, pas de changement...
J'ai oublié de préciser qu'hier j'ai essayé de modifier le code du fichier d'index en y insérant du code, il est bien interprété. Et les erreurs aussi :tongue:

**Comment by mtancoigne** [comment]
Alors, après un peu de tests et de bidouillages, j'en arrive au début de conclusion suivante : 
- Y'a un problème avec mod_rewrite (ça vient peut-être de chez moi, je dois regarder plus en détails)
- Y'a un voir, _des_ problèmes avec le chemin complet utilisé par certaines fonctions (/modules/core/classes/app/php -> errorHandlerFatal() par exemple) composée de `$_SERVER['DOCUMENT_ROOT']` et la constante `BASE_PATH` définie dans le fichier de config. Or $SERVER['DOCUMENT_ROOT'] pointe vers **/var/www**, et là, les documents sont complètement en dehors de ça... Je planche aussi là dessus
- De plus, après un essai d'install (réussi) dans /var/www/parsimony, donc, sous la racine de mon serveur, les liens pointant vers les css,js,etc de la page (générée :tada:) pointent vers des destinations étranges du genre /parsimony/core/... ou encore directement /core/...

Bref, je pense qu'il y a un soucis de ce côté là.

Quelles sont les config des machines de dev ?

**Comment by mtancoigne** [comment]
Pour commencer, les lignes contenant

``` PHP
realpath($_SERVER['DOCUMENT_ROOT']). BASE_PATH 
```

_devraient_ être changées, elles renvoient chez moi `/var/www/~mt/parsimony/`, ce qui est faux (devrait être `/home/kure/public_html/parsimony/`) . et fait tenter de créer les fichiers de session dans le mauvais répertoire :
/modules/core/classes/user.php ->l.41 : function __construct() :

``` PHP
 $this->sessPath = realpath($_SERVER['DOCUMENT_ROOT']). BASE_PATH . 'profiles' . DIRECTORY_SEPARATOR . PROFILE . DIRECTORY_SEPARATOR . 'sessions';
```

est suivi ensuite par l'éxécution de (même fichier, l.70 :)

``` PHP
$dir = $this->sessPath . DIRECTORY_SEPARATOR . $hash[0] . DIRECTORY_SEPARATOR . $hash[1] . DIRECTORY_SEPARATOR . $hash[2] . DIRECTORY_SEPARATOR . $hash[3] . DIRECTORY_SEPARATOR;
        if (!is_dir($dir))
            mkdir($dir, 0777 , true);
```

qui renvoie vers la prise en charge des messages d'erreur (`errorHandler()` app.php l.282). Or cette erreur ne peut être gérée avec ce code

``` PHP
public static function errorLog($code, $file, $line, $message) {
            self::dispatchEvent('error', array($code, $file, $line, $message));
            $root = realpath($_SERVER['DOCUMENT_ROOT']) . BASE_PATH;

            /* Log error */
            if (is_file($root . 'modules/core/errors.log'))
                file_put_contents($root . 'modules/core/errors.log', $message.'-||-'.$file.'-||-'. $line , FILE_APPEND);

        }
```

...
Une constante DOCUMENT_ROOT pourrait être définie dans le fichier de config, et l'installateur la renseignerait. Ensuite, garder cette constante sure pour les traitements relatifs aux chemins. Non ?

**Comment by parsimony** [comment]
- "J'ai oublié de préciser qu'hier j'ai essayé de modifier le code du fichier d'index en y insérant du code, il est bien interprété. --> Et les erreurs aussi <--"
  -- Quelles sont elles ?
- "Y'a un problème avec mod_rewrite"
  -- C'est possible mais tu aurais au minimum l'HTML de la première page
- errorHandlerFatal()
  -- Cette méthode est exécutée après une erreur fatale, le comportement de l'inclusion des fichiers dans PHP n'est plus le même, c'est pourquoi on doit utiliser $_SERVER['DOCUMENT_ROOT'](défini par la conf serveur, un pb a ce niveau ?)
- "les liens pointant vers les css,js,etc de la page (générée ) pointent vers des destinations étranges"
  -- quel est ton BASE_PATH ? (/config.php)
- "/parsimony/core/... ou encore directement /core/..."
  -- les 2 sur la même install, bizarre ?? sinon la génération ce fait dans le module core, donc tout est normal
-  elles renvoient chez moi /var/www/~mt/parsimony/, ce qui est faux.
  -- $_SERVER['DOCUMENT_ROOT'] récupère la valeur envoyée par la config serveur (http://www.php.net/manual/en/reserved.variables.server.php), quel est ton BASE_PATH ? (/config.php), ~mt/parsimony/ ou /parsimony/ ?

merci pour ton aide précieuse

**Comment by mtancoigne** [comment]
> > "J'ai oublié de préciser qu'hier j'ai essayé de modifier le code du fichier d'index en y insérant du code, il est bien >>interprété. --> Et les erreurs aussi <--"
> - Quelles sont elles ?
>   C'est des erreurs que j'ai mises volontairement pour les voir, essayer de comprendre...

Mon fichier  de config dit "~mt/parsimony" ce qui est logique vu que j'installe à partire de 127.0.0.1/~mt/parsimony Donc, cette ligne doit être modifiée, je la contourne maintenant en mettant `/../../home/mt/public_html/parsimony/`.
J'arrive à avoir le HTML, vu que ça contourne le `$SERVER['DOCUMENT_ROOT']` et permet donc de créer la session sans génerer de errorHandlerFatal() qui provoquait le `exit;` de la page blanche.

Mais toujours pas de css/js (je regarde les sources en ce moment.)

**Comment by mtancoigne** [comment]
Ok, l'erreur est là :)

``` HTML
...
...
<link rel="stylesheet" type="text/css" href="/../../home/mt/public_html/parsimony/concat?format=css&amp;files=/../../home/mt/public_html/parsimony/lib/cms.css,/../../home/mt/public_html/parsimony/core/desktop.css,/../../home/mt/public_html/parsimony/core/themes/parsidefault/desktop.css">
...
...
```

Les fichiers sont appelés en fonction de `$config['BASE_PATH']` que j'ai modifié.
En fait, je crois qu'il faut vraiment faire une séparation entre le chemin sur le disque et le chemin dans l'URL, car si le système est installé ailleurs que dans l'arborescence de DOCUMENT_ROOT (userdir, alias, mod_rewrite, par exemple, si je me trompe pas...), ça ne fonctionne pas, vu que le système prend pour acquis que la partie droite de l'URL (ici /~mt/parsimony) correspond à l'arborescence de DOCUMENT_ROOT (ici /var/www) et qu'il essaie de tout faire correspondre dans ses appels de fichiers...

Je continue mon investigation demain, j'ai un boulot ^^

Bonne nuit et bon courage :)

**Comment by parsimony** [comment]
En fait c'est l'utilisationde l'alias /~mt/par....   qui est à l'origine :)
Tu as mis le chemin système sur le BASE_PATH qui est utilisé pour les URL, ce qui ne fait pas bon ménage.
Je tente une install avec alias( ce qui n'est pas très courant pour un site en prod ) 

Bon courage à toi !

**Comment by mtancoigne** [comment]
Je dirais que c'est l'utilisation de `$SERVER['DOCUMENT_ROOT']` qui est à l'origine du problème, car en prod, c'est peut-être étrange, mais en dev, pas du tout...

**Comment by mtancoigne** [comment]
Bon, pour moi le problème est résolu an modifiant les fichiers suivants

``` PHP
// fichier /config.php, L4
define('REAL_BASEPATH', '/home/mt/public_html/parsimony/');

//
// fichier /modules/core/classes/user.php, L41 remplacement de 
$this->sessPath = realpath($_SERVER['DOCUMENT_ROOT']). BASE_PATH . 'profiles' . DIRECTORY_SEPARATOR . PROFILE . DIRECTORY_SEPARATOR . 'sessions';
//par :
$this->sessPath = REAL_BASEPATH . 'profiles' . DIRECTORY_SEPARATOR . PROFILE . DIRECTORY_SEPARATOR . 'sessions';

//
//fichier /modules/core/classes/app.php, L301 remplacement de 
$root = realpath($_SERVER['DOCUMENT_ROOT']) . BASE_PATH;
//par
$root = REAL_BASEPATH;

//et L336 de ce même fichier, remplacement de 
$root = realpath($_SERVER['DOCUMENT_ROOT']) . BASE_PATH;
//par 
$root = REAL_BASEPATH;
```

Parsimony fonctionne comme un charme dans mon userdir. Et je suis persuadé qu'il fonctionnera tout aussi bien ailleurs

**Comment by mtancoigne** [comment]
Et le pb vient bien du mélange de `$_SERVER['DOCUMENT_ROOT']` avec des morceaux d'URL (`$config['BASE_PATH'] qui est créée à partir de l'URL...)

Je vasi taffer, je rentre ce midi si y'a du changement.

**Comment by parsimony** [comment]
Exact! :+1: 

Donc pour résumer, quand on utilise Parsimony avec le mod user_dir, il faut impérativement placer le rewrite base dans le .htaccess de la racine; je vais le rajouter en commentaire puis dans la doc.

`RewriteBase /~username/parsimony`

Ensuite effectivement, le mod UserDir modifiait le `$_SERVER['DOCUMENT_ROOT']` , il n'est donc pas utilisable si l'on veut une compatibilité avec le mod UserDir .

Pour cela les modifications que tu évoquées sont les bonnes, j'ai juste un petit grain à ajouter, à savoir la constante **DIR** prédéfinie par PHP depuis la v 5.3.0. (petit article http://blog.pascal-martin.fr/post/php-5.3-constante-magique-__DIR__)

Ainsi si l'on rajoute dans le fichier config.php `$config['DOCUMENT_ROOT'] = __DIR__;`

Aucun calcul, juste une affectation.

on peu ensuite utiliser celui-ci via `\app::$config['DOCUMENT_ROOT']`

Encore merci d' avoir contribué à l'amélioration de la compatibilité de Parsimony :+1:

**Comment by mtancoigne** [comment]
Pas de soucis, je compte bien m'en servir, de ce soft :)

**Comment by parsimony** [comment]
:)

**Comment by arkanje** [comment]
Bonjour.

Je viens d'installer Parsimony et après le clic sur "Lets go", je me retrouve également avec une page blanche.

J'ai ajouté le code pour afficher les possibles erreurs PHP mais rien ne s'affiche après un rafraichissement.
J'ai suivi la discussion mais il s'avère que la version que j'ai contient déjà les corrections concernant la variable `$_SERVER['DOCUMENT_ROOT']`...

J'ai testé ces instructions:

```
echo realpath($_SERVER['DOCUMENT_ROOT']);
echo "<br>";
echo __DIR__;
```

et voici le résultat:

```
C:\Program Files\EasyPHP-12.1\www
C:\Program Files\EasyPHP-12.1\home
```

J'ai tenté de modifier le fichier config.php avec ce qui suit:
`$config['DOCUMENT_ROOT'] = 'C:/Program Files/EasyPHP-12.1/www';`

Mais sans succès... 
J'ai toujours une page blanche avec `/index.php?parsiurl=connect` et `/connect`.

Avec `/connect`, si je supprime le fichier `.htaccess`, j'ai l'erreur suivante:

```
Objet non trouvé!

L'URL demandée n'a pas pu être trouvée sur ce serveur. Si vous avez tapé l'URL à la main, veuillez vérifier l'orthographe et réessayer.

Si vous pensez qu'il s'agit d'une erreur du serveur, veuillez contacter le webmestre.

Error 404

127.0.0.1
Apache/2.4.2 (Win32) PHP/5.4.6
```

Pouvez-vous m'aider à résoudre ce souci?

Merci.

**Comment by parsimony** [comment]
Je viens d'installer Parsimony avec EasyPHP-12.1 (installé quelques minutes auparavant avec les configurations par défaut) sur Win7, et aucun problème..
Avez-vous téléchargé la dernière version ? Avez -vous modifié la configuration par défaut de EasyPHP ? Vous pouvez aussi essayer de l'installer sur WampServer.

**Comment by arkanje** [comment]
J'ai trouvé la source du problème!

Si je passe la variable `$config['domain']['multisite']` de 1 à 0 tout rentre dans l'ordre...

**Comment by parsimony** [comment]
Merci pour ce retour qui viendra enrichir la doc :+1:
